#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: tools/aggregate-git-compat-random.sh [result_dir]

Collect and summarize .record.tsv files generated by tools/run-git-compat-random.sh.
EOF
}

if [ "${1:-}" = "--help" ]; then
  usage
  exit 0
fi

result_dir="${1:-compat-random-results}"
if [ ! -d "$result_dir" ]; then
  echo "result directory not found: $result_dir" >&2
  exit 1
fi

mapfile -t record_files < <(find "$result_dir" -type f -name '*.record.tsv' | sort)
if [ "${#record_files[@]}" -eq 0 ]; then
  echo "no compat-random result files found under $result_dir" >&2
  exit 1
fi

total=0
success=0
failure=0
duration_sum=0
duration_min=""
duration_max=""
failed_lines=""

for file in "${record_files[@]}"; do
  while IFS=',' read -r run_id run_ts seed seed_source main_head main_head_short ratio shard shards status exit_code duration test_count tests log_file; do
    if [ "$run_id" = "run_id" ]; then
      continue
    fi
    total=$((total + 1))
    if [ "$status" = "success" ]; then
      success=$((success + 1))
    else
      failure=$((failure + 1))
      if [ -z "$tests" ]; then
        tests="unknown"
      fi
      if [ -z "$log_file" ]; then
        log_file="$result_dir/$run_id/compat-shard-${shard}-of-${shards}.log"
      fi
      rerun_cmd="bash tools/run-git-compat-random.sh --seed \"$seed\" --shard \"$shard\" --shards \"$shards\" --ratio \"$ratio\""
      failed_lines+="${run_ts} run_id=${run_id} shard=${shard}/${shards} seed=${seed} exit=${exit_code} duration=${duration}s head=${main_head_short} status=${status}"$'\n'
      failed_lines+="  - seed_source: ${seed_source}"$'\n'
      failed_lines+="  - tests: ${tests}"$'\n'
      failed_lines+="  - log: ${log_file}"$'\n'
      failed_lines+="  - rerun_cmd: ${rerun_cmd}"$'\n'$'\n'
    fi
    if [ "$duration_sum" -eq 0 ] && [ "$duration_min" = "" ]; then
      duration_min="$duration"
      duration_max="$duration"
    else
      if [ "$duration" -lt "$duration_min" ]; then
        duration_min="$duration"
      fi
      if [ "$duration" -gt "$duration_max" ]; then
        duration_max="$duration"
      fi
    fi
    duration_sum=$((duration_sum + duration))
  done < "$file"
done

if [ "$total" -eq 0 ]; then
  echo "no result rows parsed in $result_dir" >&2
  exit 1
fi

success_rate_num=$((success * 10000 / total))
success_rate_int=$((success_rate_num / 100))
success_rate_frac=$((success_rate_num % 100))

echo "# git-compat random aggregate"
echo "result_dir: $result_dir"
echo "files: ${#record_files[@]}"
echo "runs: $total"
echo "success: $success"
echo "failure: $failure"
printf 'success_rate: %d.%02d%%\n' "$success_rate_int" "$success_rate_frac"
echo "duration_sum_sec: $duration_sum"
echo "duration_avg_sec: $((duration_sum / total))"
echo "duration_min_sec: ${duration_min:-0}"
echo "duration_max_sec: ${duration_max:-0}"
echo
echo "## failures"
if [ "$failure" -eq 0 ]; then
  echo "- none"
else
  printf '%s' "$failed_lines"
fi
